server.port=${PORT:8080}
logging.level.org.atmosphere=warn

# Launch the default browser when starting the application in development mode
vaadin.launch-browser=true

# Vaadin scans these packages for @Route views
vaadin.allowed-packages=com.vaadin,org.vaadin,at.spengergasse.lager
